# -*- coding: utf-8 -*-
"""AES+Stega_demo_code.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KxPL6PG0Bx7Ke2xk25yXi-7HOBJeiEo6
"""

pip install pycrypto

# AES
import hashlib
import math
import os

from Crypto.Cipher import AES

# steganogrphy (Image)
from PIL import Image
import numpy as np

IV_SIZE = 16 # but in real 128
KEY_SIZE = 32 # 256
SALT_SIZE = 16 


# clearText is your Input or Message
clearText = b"bomb in car"
password = b"criminals"

#encryption

salt = os.urandom(SALT_SIZE)

derived = hashlib.pbkdf2_hmac('sha256',password, salt , 100000, dklen = IV_SIZE + KEY_SIZE)

iv = derived[0:IV_SIZE]
key = derived[IV_SIZE:]

encrypted = salt + AES.new(key, AES.MODE_CFB, iv ).encrypt(clearText)

print(encrypted)







"""This is just a demo 

If you want Full Project Code with Report then..

#Mail me now at vatshayan007@gmail.com 
"""





